"""added expiry field in password reset tokens

Revision ID: 5ebf3710765c
Revises: 144eb581a434
Create Date: 2026-01-06 13:30:17.673489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ebf3710765c'
down_revision: Union[str, Sequence[str], None] = '144eb581a434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwordresettokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passwordresettokens', 'expires_at')
    # ### end Alembic commands ###
