"""is used field added

Revision ID: 777c50f69a53
Revises: 6de5d80683d5
Create Date: 2026-01-06 15:00:19.060770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '777c50f69a53'
down_revision: Union[str, Sequence[str], None] = '6de5d80683d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwordresettokens', sa.Column('is_used', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passwordresettokens', 'is_used')
    # ### end Alembic commands ###
